In [ ]:
"""
案例：癌症分类预测-良／恶性乳腺癌肿瘤预测
流程分析:
    1.数据获取
        读取的时候加上names
    2.数据处理
        缺失值处理
    3.数据集划分
    4.特征工程:
        无量纲化处理: 标准化
    5.逻辑回归预估器
    6.模型评估
"""

In [5]:
import pandas as pd
import numpy as np

In [6]:
# 1. 数据获取
column_name = ['Sample code number','Clump Thickness','Uniformity of Cell Size','Uniformity of Cell Shape',
               'Marginal Adhesion','Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin','Normal Nucleoli',
               'Mitoses','Class']
data = pd.read_csv('./cancer/breast-cancer-wisconsin.data',names=column_name)

In [7]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [8]:
# 2. 缺失值处理
# 1) 替换-->np.nan
data = data.replace(to_replace='?', value = np.nan)
# 2) 删除缺失样本
data.dropna(inplace=True)

In [9]:
data.isnull().any() # 不存在缺失值

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [12]:
# 3. 数据集划分
x = data.iloc[:,1:-1]
y = data['Class']

In [13]:
x.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1   
1                5                        4                         4   
2                3                        1                         1   
3                6                        8                         8   
4                4                        1                         1   

   Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
0                  1                            2           1   
1                  5                            7          10   
2                  1                            2           2   
3                  1                            3           4   
4                  3                            2           1   

   Bland Chromatin  Normal Nucleoli  Mitoses  
0                3                1        1  
1                3                2        1  
2                3                1        1  
3                3                7        1  
4                3                1        1

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=23)

In [17]:
# 4.特征工程
from sklearn.preprocessing import StandardScaler

In [18]:
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

In [19]:
# 5.预估器模型
from sklearn.linear_model import LogisticRegression

In [20]:
estimator = LogisticRegression()
estimator.fit(x_train, y_train)

LogisticRegression()

In [21]:
# 逻辑回归的系数权重和偏置
estimator.coef_

array([[ 1.40150708, -0.01308266,  0.68569103,  0.85940743,  0.27100373,
         1.27668137,  1.00989692,  0.75626386,  0.76710949]])

In [22]:
estimator.intercept_

array([-1.20085654])

In [24]:
# 6. 模型评估
# 方法一: 直接对比真实值和预测值
y_predict = estimator.predict(x_test)
print('y_predict: \n', y_predict)
print('直接对比真实值和预测值: \n', y_test == y_predict)

# 方法二: 计算准确率
score = estimator.score(x_test, y_test)
print('准确率: \n', score)


y_predict: 
 [2 2 2 2 2 4 4 4 4 2 2 2 2 4 2 2 2 2 4 2 4 2 2 2 4 4 4 2 2 2 4 4 2 2 2 4 4
 2 2 2 4 2 2 2 4 4 2 2 4 2 4 4 2 4 2 2 4 4 4 2 2 2 4 4 4 2 2 2 2 4 2 2 2 2
 2 2 2 4 2 2 2 2 2 4 2 2 2 4 4 2 4 4 4 2 4 4 2 2 4 2 2 2 2 4 4 4 4 2 2 2 4
 4 4 4 2 2 4 2 2 4 4 2 2 2 2 2 4 4 2 2 2 2 4 2 2 2 4 4 2 4 2 2 2 2 4 2 2 4
 4 2 2 2 4 2 2 2 4 2 4 2 4 4 2 2 2 2 2 2 4 2 4]
直接对比真实值和预测值: 
 119     True
30      True
76      True
27      True
489    False
       ...  
241     True
116     True
608     True
95      True
54      True
Name: Class, Length: 171, dtype: bool
准确率: 
 0.9766081871345029


In [25]:
# 查看精确率, 召回率 , F1-score
from sklearn.metrics import classification_report

In [26]:
report = classification_report(y_test, y_predict, labels=[2,4], target_names=['良性','恶性'])

In [28]:
print(report)

              precision    recall  f1-score   support

          良性       0.98      0.98      0.98       106
          恶性       0.97      0.97      0.97        65

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171



In [29]:
y_test.head()

119    2
30     2
76     2
27     2
489    4
Name: Class, dtype: int64

In [30]:
# y_true:每个样本的真实类别，必须为0(反例),1(正例)标记
# 将y_test 转化成 0,1
y_true = np.where(y_test > 3 , 1 , 0) # 三元运算符

In [31]:
y_true

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [32]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_true, y_predict)

0.9751814223512337